### ISSUE TITLE
Вторая задача

### ISSUE THREAD

**Issue by Sammers21** [HsAnalytics/hs_backend#2]
Нужно написать небольшой сервер, который будет отдавать html страничку с формочкой для ввода токена и username. 

После ввода пользователем token'a и username сервер выводит в консоль историю игр пользователя

Документация по vert.x core - http://vertx.io/docs/vertx-core/java/

**Comment by Sammers21** [comment]
как успехи?

**Comment by Vadim128** [comment]
замерджил в html_form
